feat: add stat service
RuslanBoo/java-explore-with-me pull request #5
Opened 2023-04-20 18:50 UTC by RuslanBoo

2023-04-20 18:54 UTC, RuslanBoo commented
Буду признателен за наводку для переделки репозитория, сейчас не нравится что методы почти одинаковые. В идеале хотелось бы через некий билдер собрать нужный запрос

2023-04-21 15:17 UTC, AnastasiyaFomkina commented
> Буду признателен за наводку для переделки репозитория, сейчас не нравится что методы почти одинаковые. В идеале хотелось бы через некий билдер собрать нужный запрос

Можно попробовать [Criteria Queries](https://www.baeldung.com/hibernate-criteria-queries)

2023-04-21 15:27 UTC, AnastasiyaFomkina requested changes

2023-04-21 15:27 UTC, AnastasiyaFomkina commented on stats/stats-client/src/main/java/ru/practicum/client/StatClientImpl.java
> +                Object.class);
Лучше сузить до более конкретного объекта, так как можем получить мискаст

2023-04-21 15:27 UTC, AnastasiyaFomkina commented on stats/stats-client/src/main/java/ru/practicum/client/StatClientImpl.java
> +                Object.class,
И здесь. Мы же знаем, какое dto нам приходит

2023-04-21 15:27 UTC, AnastasiyaFomkina commented on stats/stats-dto/src/main/java/ru/practicum/EndpointHitDto.java
> +            regexp = "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$")
WOW

2023-04-21 15:27 UTC, AnastasiyaFomkina commented on stats/stats-dto/src/main/java/ru/practicum/EndpointHitDto.java
> +    LocalDateTime timestamp;
Нужно добавить модификаторы доступа для полей

2023-04-21 15:27 UTC, AnastasiyaFomkina commented on stats/stats-dto/src/main/java/ru/practicum/ViewStatsDto.java
> +    long hits;
Не хватает модификаторов доступа

2023-04-21 15:27 UTC, AnastasiyaFomkina commented on stats/stats-server/src/main/java/ru/practicum/controller/StatController.java
> +    public ResponseEntity<Object> saveHit(@Validated @RequestBody EndpointHitDto endpointHitDto) {
Лучше возвращать конкретный объект, а не максимально абстрактный `Object`

2023-04-21 15:27 UTC, AnastasiyaFomkina commented on stats/stats-server/src/main/java/ru/practicum/model/EndpointHit.java
> +    String ip;
Не хватает модификаторов доступа

2023-04-22 13:50 UTC, AnastasiyaFomkina approved these changes

2023-04-22 18:10 UTC, merged