feat: add main service
RuslanBoo/java-explore-with-me pull request #6
Opened 2023-06-12 10:13 UTC by RuslanBoo

2023-06-12 16:45 UTC, AnastasiyaFomkina requested changes
Отличная работа, молодец 🔥

2023-06-12 16:45 UTC, AnastasiyaFomkina commented on ewm-service/src/main/java/ru/practicum/categories/CategoryMapper.java
> +import org.mapstruct.*;
Лучше явно объявлять все импотры

2023-06-12 16:45 UTC, AnastasiyaFomkina commented on ewm-service/src/main/java/ru/practicum/categories/model/Category.java
> +    String name;
Нужно добавить модификатор доступа здесь и всем полям во всех моделях и dto - объектах, где он отсутствует

2023-06-12 16:45 UTC, AnastasiyaFomkina commented on ewm-service/src/main/java/ru/practicum/categories/service/CategoryServiceHelper.java
> +    public Category findById(int id) {
Метод нигде не используется

2023-06-12 17:43 UTC, RuslanBoo commented on ewm-service/src/main/java/ru/practicum/categories/service/CategoryServiceHelper.java
> +    public Category findById(int id) {
Привет! Этот класс нужен для EventMapper, обозначен в аннотации @Mapper(uses = "тут класс"). У маппера контракт по методу findById(), можно посмотреть как использует в сгенерированном ImpMapper файле - */ewm-service/target/classes/ru/practicum/events/EventMapperImpl.class

2023-06-12 17:43 UTC, RuslanBoo commented on ewm-service/src/main/java/ru/practicum/categories/CategoryMapper.java
> +import org.mapstruct.*;
Передалал все импорты

2023-06-12 17:44 UTC, RuslanBoo commented on ewm-service/src/main/java/ru/practicum/categories/model/Category.java
> +    String name;
Добавил  модификаторы

2023-06-13 05:59 UTC, AnastasiyaFomkina approved these changes

2023-06-13 15:57 UTC, merged